project:
  type: website

website:
  title: "Mon_site"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

